
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace RecommendingMLModel_ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            RecommendingMLModel.ModelInput sampleData = new RecommendingMLModel.ModelInput()
            {
                NguoiDungId = @"01256764-b3ac-4e6f-a060-58411d63f3b0",
                PhongTroId = 8F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = RecommendingMLModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");


            Console.WriteLine($"NguoiDungId: {@"01256764-b3ac-4e6f-a060-58411d63f3b0"}");
            Console.WriteLine($"PhongTroId: {8F}");
            Console.WriteLine($"Rating: {5F}");


            Console.WriteLine($"\n\nPredicted Rating: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
